name: 'Deploy'
on:
  push:
    branches:
    - master

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Terraform to Azure      
      env:
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_RESOURCE_GROUP_NAME: ${{ secrets.ARM_RESOURCE_GROUP_NAME }}
      run: |
        set -euxo pipefail
        
        export TF_VAR_client_id=$ARM_CLIENT_ID
        export TF_VAR_client_secret=$ARM_CLIENT_SECRET
        export TF_VAR_resource_group_name=$ARM_RESOURCE_GROUP_NAME
        
        # az login --service-principal --user $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
   
        ###
        echo "Installing Terraform"
        sudo apt-get install unzip
        wget https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
        unzip terraform_0.12.9_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version 
        
        ###
        echo "Deploying Terraform"
        terraform init  -input=false -upgrade examples/simple
        terraform plan  -input=false examples/simple
        terraform apply -input=false -auto-approve examples/simple
