name: 'Deploy'
on:
  push:
    branches:
    - master

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: bash
    - name: Run a one-line script
      run: |
        set -euxo pipefail
   
        # These are regular pipeline variables
        echo ARM_SUBSCRIPTION_NAME = $ARM_SUBSCRIPTION_NAME
