name: 'Deploy'
on:
  push:
    branches:
    - master

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Terraform to Azure      
      env: # Or as an environment variable
        ARM_SUBSCRIPTION_NAME: ${{ secrets.ARM_SUBSCRIPTION_NAME }}
      run: |
        set -euxo pipefail
   
        # These are regular pipeline variables
        echo ARM_SUBSCRIPTION_NAME = $ARM_SUBSCRIPTION_NAME
